openapi: 3.1.0
info:
  version: 1.0.0
  title: Bike Sharing Web Application
  contact:
    email: adhikariratna52@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  description: |
    This is API definitions following the OpenAPI
    specification for the bike sharing app.

    # Introduction

    In this API documentation, we describe our APIs in [OpenAPI/Swaggerformat](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md).
    Basically, we have get all bikes API and update bike's rent status API. More details on those APIs 
    can be seen in next section.
tags:
  - name: Bike
    description: API endpoints for getting bikes and updating the bike's rent status.
servers:
  - url: 'http://localhost:3000/api'
paths:
  '/bikes':
    get:
      tags:
        - Bike
      summary: Get all bikes
      description: |
        To get all bikes from the database
      operationId: getBikes
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bikes'
              example:
                [
                  {
                    id: sdf,
                    name: bike,
                    latitude: 20.33,
                    longitude: 3.44,
                    rented: false,
                    sessionId: ''
                  }
                ]

        '500':
          description: Internal Server Error
        '404':
          description: Bikes not found
    patch:
      tags:
        - Bike
      summary: Update bike's rent status
      description: User session id should be sent in order to update bike's rent status 
      operationId: updateBike
      responses:
        '200':
          description: OK
        '400':
          description: |
            User has already rented one bike
            OR User cannot return someone else's bike
            OR Bike not rented yet
        '404':
          description: Bike not found
        '500':
          description: Internal Server Error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BikePayload'
        description: Updated bike object
        required: true
  
components:
  schemas:
    Bike:
      type: object
      properties:
        id:
          description: Object Id generated by MongoDB
          type: string
          example: 3421
        name:
          description: Bike name
          type: string
          minLength: 1
          example: Bike 12
        latitude:
          description: Bike position
          type: number
          minLength: 1
          example: 40.3434
        longitude:
          description: Bike position
          type: number
          minLength: 1
          example: 5.34
        rented:
          description: Bike available status
          type: boolean
          example: true
        sessionId:
          description: User session Id from browser
          type: string
          example: 344sd
    Bikes:
      type: array
      items:
        $ref: '#/components/schemas/Bike'
    BikePayload:
      type: object
      properties:
        id:
          description: Object Id generated by MongoDB
          type: string
          example: 3421
          minLength: 1
        rented:
          description: Bike available status
          type: boolean
          example: true
          minLength: 1
        sessionId:
          description: User session Id from browser
          type: string
          example: 344sd
          minLength: 1